[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  MODE = "production"

[context.branch-deploy.environment]
  MODE = "development"

[context.production.environment]  
  MODE = "production"
